/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    includeBuild("gradle-plugin") {
        name = "gradle-plugin-build"
    }

    plugins {
        id("com.gradleup.shadow") version providers.gradleProperty("shadowVersion")
        id("fabric-loom") version providers.gradleProperty("fabricLoomVersion")
        id("net.neoforged.moddev") version providers.gradleProperty("neoforgeModdevVersion")
        id("org.spongepowered.gradle.vanilla") version providers.gradleProperty("vanillaGradleVersion")
    }

    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven("https://repo.papermc.io/repository/maven-public/")
        maven("https://maven.fabricmc.net/")
        maven("https://maven.neoforged.net/releases/")
        maven("https://repo.spongepowered.org/repository/maven-public/")
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version providers.gradleProperty("foojayResolverVersion")
}

rootProject.name = "RapunzelLib"

include(
    "api",
    "bom",
    "common",
    "commands",
    "commands-shared",
    "commands-paper",
    "commands-fabric",
    "commands-neoforge",
    "commands-sponge",
    "events",
    "events-shared",
    "events-paper",
    "events-fabric",
    "events-neoforge",
    "events-sponge",
    "gui",
    "gui-shared",
    "gui-fabric",
    "gui-neoforge",
    "gui-paper",
    "gui-sponge",
    "inventory",
    "inventory-shared",
    "inventory-paper",
    "inventory-fabric",
    "inventory-neoforge",
    "inventory-sponge",
    "network",
    "database-spool",
    "nbt",
    "nbt-shared",
    "nbt-paper",
    "nbt-fabric",
    "nbt-neoforge",
    "nbt-sponge",
    "platform-shared",
    "platform-paper",
    "platform-fabric",
    "platform-velocity",
    "platform-neoforge",
    "platform-sponge",
    "gradle-plugin",
)

// Workaround for NeoForge ModDev (net.neoforged.moddev) IntelliJ sync:
// During IntelliJ import (`idea.sync.active=true`), ModDev applies idea-ext on the root project.
// When multiple NeoForge subprojects do that in the same import, it can clash on the root "settings" extension.
// Limit the IntelliJ-specific integration to the platform module during sync.
val originalIdeaSyncActive: String? = System.getProperty("idea.sync.active")
val disableIdeaSyncForProjects = setOf(":commands-neoforge", ":events-neoforge", ":nbt-neoforge", ":gui-neoforge", ":inventory-neoforge")
val ideaSyncKey = "idea.sync.active"

fun restoreIdeaSyncProperty() {
    if (originalIdeaSyncActive == null) {
        System.clearProperty(ideaSyncKey)
    } else {
        System.setProperty(ideaSyncKey, originalIdeaSyncActive)
    }
}

gradle.beforeProject {
    val project = this
    if (originalIdeaSyncActive == "true" && project.path in disableIdeaSyncForProjects) {
        System.setProperty(ideaSyncKey, "false")
    }
}

gradle.afterProject {
    val project = this
    if (originalIdeaSyncActive == "true" && project.path in disableIdeaSyncForProjects) {
        restoreIdeaSyncProperty()
    }
}
