/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    val minecraftTargets = java.util.Properties().apply {
        file("gradle/minecraft-targets.properties").inputStream().use { load(it) }
    }

    fun targetToken(target: String): String =
        target.replace(Regex("[^A-Za-z0-9]"), "_")

    val activeMinecraftTarget =
        providers.gradleProperty("rapunzellib.minecraftTarget").orNull
            ?: providers.gradleProperty("rapunzellib.minecraftCoreVersion").orNull
            ?: minecraftTargets.getProperty("core")
            ?: error("No core Minecraft target configured")

    fun targetProperty(key: String): String? =
        minecraftTargets.getProperty("target.${targetToken(activeMinecraftTarget)}.$key")

    fun pluginVersion(alias: String, legacyProperty: String): String =
        providers.gradleProperty("rapunzellib.plugin.$alias").orNull
            ?: targetProperty("plugin.$alias")
            ?: minecraftTargets.getProperty("plugin.$alias")
            ?: providers.gradleProperty(legacyProperty).orNull
            ?: error("No plugin version configured for $alias")

    val shadowPluginVersion = pluginVersion("shadow", "shadowVersion")
    val fabricLoomPluginVersion = pluginVersion("fabric-loom", "fabricLoomVersion")
    val neoforgeModdevPluginVersion = pluginVersion("neoforge-moddev", "neoforgeModdevVersion")
    val vanillaGradlePluginVersion = pluginVersion("vanilla-gradle", "vanillaGradleVersion")
    val paperweightUserdevPluginVersion = pluginVersion("paperweight-userdev", "paperweightUserdevVersion")

    includeBuild("gradle-plugin") {
        name = "gradle-plugin-build"
    }

    includeBuild("visualizer") {
        name = "visualizer-build"
    }

    resolutionStrategy {
        eachPlugin {
            when (requested.id.id) {
                "com.gradleup.shadow" -> useVersion(shadowPluginVersion)
                "net.fabricmc.fabric-loom" -> useVersion(fabricLoomPluginVersion)
                "net.neoforged.moddev" -> useVersion(neoforgeModdevPluginVersion)
                "org.spongepowered.gradle.vanilla" -> useVersion(vanillaGradlePluginVersion)
                "io.papermc.paperweight.userdev" -> useVersion(paperweightUserdevPluginVersion)
            }
        }
    }

    plugins {
        id("com.gradleup.shadow") version shadowPluginVersion
        id("net.fabricmc.fabric-loom") version fabricLoomPluginVersion
        id("net.neoforged.moddev") version neoforgeModdevPluginVersion
        id("org.spongepowered.gradle.vanilla") version vanillaGradlePluginVersion
        id("io.papermc.paperweight.userdev") version paperweightUserdevPluginVersion
    }

    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven("https://repo.papermc.io/repository/maven-public/")
        maven("https://maven.fabricmc.net/")
        maven("https://maven.neoforged.net/releases/")
        maven("https://repo.spongepowered.org/repository/maven-public/")
        maven("https://repo.opencollab.dev/maven-snapshots")
        maven("https://repo.opencollab.dev/maven-releases")
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version providers.gradleProperty("foojayResolverVersion")
}

rootProject.name = "RapunzelLib"

include(
    "api",
    "bom",
    "common",
    "livetest",
    "livetest-shared",
    "livetest-paper",
    "livetest-fabric",
    "livetest-neoforge",
    "livetest-sponge",
    "commands",
    "commands-shared",
    "commands-paper",
    "commands-fabric",
    "commands-neoforge",
    "commands-sponge",
    "events",
    "events-shared",
    "events-paper",
    "events-fabric",
    "events-neoforge",
    "events-sponge",
    "gui",
    "gui-shared",
    "gui-paper",
    "gui-fabric",
    "gui-neoforge",
    "gui-sponge",
    "inventory",
    "inventory-shared",
    "inventory-paper",
    "inventory-fabric",
    "inventory-neoforge",
    "inventory-sponge",
    "network",
    "database-spool",
    "nbt",
    "nbt-shared",
    "nbt-paper",
    "nbt-fabric",
    "nbt-neoforge",
    "nbt-sponge",
    "platform-shared",
    "platform-paper",
    "platform-fabric",
    "platform-velocity",
    "platform-neoforge",
    "platform-sponge",
    "visuals",
    "visuals-shared",
    "visuals-paper",
    "visuals-fabric",
    "visuals-neoforge",
    "visuals-sponge",
    "gradle-plugin",
)

// Workaround for NeoForge ModDev (net.neoforged.moddev) IntelliJ sync:
// During IntelliJ import (`idea.sync.active=true`), ModDev applies idea-ext on the root project.
// When multiple NeoForge subprojects do that in the same import, it can clash on the root "settings" extension.
// Limit the IntelliJ-specific integration to the platform module during sync.
val originalIdeaSyncActive: String? = System.getProperty("idea.sync.active")
val disableIdeaSyncForProjects = setOf(":commands-neoforge", ":events-neoforge", ":nbt-neoforge", ":gui-neoforge", ":inventory-neoforge")
val ideaSyncKey = "idea.sync.active"

fun restoreIdeaSyncProperty() {
    if (originalIdeaSyncActive == null) {
        System.clearProperty(ideaSyncKey)
    } else {
        System.setProperty(ideaSyncKey, originalIdeaSyncActive)
    }
}

gradle.beforeProject {
    val project = this
    if (originalIdeaSyncActive == "true" && project.path in disableIdeaSyncForProjects) {
        System.setProperty(ideaSyncKey, "false")
    }
}

gradle.afterProject {
    val project = this
    if (originalIdeaSyncActive == "true" && project.path in disableIdeaSyncForProjects) {
        restoreIdeaSyncProperty()
    }
}
