/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven("https://repo.papermc.io/repository/maven-public/")
        maven("https://maven.fabricmc.net/")
        maven("https://maven.velocitypowered.com/snapshot/")
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

rootProject.name = "RapunzelLib"

include(
    "api",
    "common",
    "commands",
    "commands-paper",
    "commands-fabric",
    "events",
    "events-paper",
    "events-fabric",
    "network",
    "database-spool",
    "platform-paper",
    "platform-fabric",
    "platform-velocity",
    "tool-server-runner",
    "gradle-plugin",
)

