package de.t14d3.rapunzellib.gradle.catalog;

import org.gradle.api.GradleException;

import java.io.File;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public final class KeyCatalogGenerator {
    private static final Map<String, RuntimeRegistryHelperSpec> RUNTIME_REGISTRY_HELPERS = Map.of(
        "entity-types",
        new RuntimeRegistryHelperSpec(
            "EntityTypes",
            List.of("de.t14d3.rapunzellib.registry.REntityType"),
            "REntityType",
            "REntityType.find(key)",
            "REntityType.require(key)"
        ),
        "item-types",
        new RuntimeRegistryHelperSpec(
            "ItemTypes",
            List.of("de.t14d3.rapunzellib.registry.RItemType"),
            "RItemType",
            "RItemType.find(key)",
            "RItemType.require(key)"
        ),
        "block-types",
        new RuntimeRegistryHelperSpec(
            "BlockTypes",
            List.of("de.t14d3.rapunzellib.Rapunzel", "de.t14d3.rapunzellib.registry.RBlockType"),
            "RBlockType",
            "Rapunzel.blockTypes().find(key)",
            "Rapunzel.blockTypes().require(key)"
        )
    );

    private KeyCatalogGenerator() {
    }

    public static List<NamespacedKeyEntry> parseInputFiles(Iterable<File> files) {
        return CatalogCodegenSupport.parseNamespacedKeyInputs(files, "key catalog");
    }

    public static String renderJavaSource(
        String packageName,
        String className,
        String domainName,
        List<NamespacedKeyEntry> keys,
        Set<String> registryHelpers
    ) {
        CatalogCodegenSupport.requireValidPackageName(packageName, "Key catalog");
        CatalogCodegenSupport.requireValidJavaIdentifier(className, "class name", "Key catalog");

        String trimmedDomainName = domainName.trim();
        if (trimmedDomainName.isEmpty()) {
            throw new GradleException("Key catalog domain name must not be blank.");
        }
        if (keys.isEmpty()) {
            throw new GradleException("Key catalog generation requires at least one namespaced key.");
        }

        Map<String, List<NamespacedKeyEntry>> grouped = keys.stream().collect(
            java.util.stream.Collectors.groupingBy(
                NamespacedKeyEntry::namespace,
                java.util.LinkedHashMap::new,
                java.util.stream.Collectors.toList()
            )
        );
        Map<String, String> namespaceNames = CatalogCodegenSupport.uniqueClassNames(new ArrayList<>(grouped.keySet()));
        List<RuntimeRegistryHelperSpec> helperSpecs = resolveRegistryHelpers(registryHelpers);
        LinkedHashSet<String> imports = new LinkedHashSet<>();
        imports.add("de.t14d3.rapunzellib.objects.RKey");
        if (!helperSpecs.isEmpty()) {
            imports.add("java.util.Optional");
            for (RuntimeRegistryHelperSpec spec : helperSpecs) {
                imports.addAll(spec.importTypes());
            }
        }

        StringBuilder source = new StringBuilder();
        source.append("package ").append(packageName).append(";\n\n");
        for (String importName : imports) {
            source.append("import ").append(importName).append(";\n");
        }
        source.append("\n/**\n")
            .append(" * Generated by rapunzellibGenerateKeyCatalog for the '").append(trimmedDomainName).append("' domain.\n")
            .append(" * Input files use one namespace:path entry per line.\n")
            .append(" * Catalog keys are convenience constants; live registries remain the source of truth.\n")
            .append(" */\n")
            .append("public final class ").append(className).append(" {\n")
            .append("    public static final String DOMAIN = ").append(CatalogCodegenSupport.javaString(trimmedDomainName)).append(";\n\n")
            .append("    private ").append(className).append("() {\n")
            .append("    }\n");

        grouped.entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(entry -> {
            String namespace = entry.getKey();
            List<NamespacedKeyEntry> namespaceKeys = new ArrayList<>(entry.getValue());
            namespaceKeys.sort(java.util.Comparator.comparing(NamespacedKeyEntry::path));
            Map<String, String> constantNames = CatalogCodegenSupport.uniqueConstantNames(
                namespaceKeys.stream().map(NamespacedKeyEntry::path).toList()
            );

            source.append("\n")
                .append("    public static final class ").append(namespaceNames.get(namespace)).append(" {\n")
                .append("        public static final String NAMESPACE = ").append(CatalogCodegenSupport.javaString(namespace)).append(";\n");
            for (NamespacedKeyEntry key : namespaceKeys) {
                source.append("\n")
                    .append("        public static final RKey ")
                    .append(constantNames.get(key.path()))
                    .append(" = RKey.of(")
                    .append(CatalogCodegenSupport.javaString(key.value()))
                    .append(");\n");
            }
            source.append("\n")
                .append("        private ").append(namespaceNames.get(namespace)).append("() {\n")
                .append("        }\n")
                .append("    }\n");
        });

        for (RuntimeRegistryHelperSpec spec : helperSpecs) {
            source.append("\n")
                .append("    public static final class ").append(spec.className()).append(" {\n")
                .append("        public static Optional<").append(spec.returnType()).append("> resolve(RKey key) {\n")
                .append("            return ").append(spec.resolveExpression()).append(";\n")
                .append("        }\n\n")
                .append("        public static ").append(spec.returnType()).append(" require(RKey key) {\n")
                .append("            return ").append(spec.requireExpression()).append(";\n")
                .append("        }\n\n")
                .append("        private ").append(spec.className()).append("() {\n")
                .append("        }\n")
                .append("    }\n");
        }

        source.append("}\n");
        return source.toString();
    }

    public static String renderJavaSource(
        String packageName,
        String className,
        String domainName,
        List<NamespacedKeyEntry> keys
    ) {
        return renderJavaSource(packageName, className, domainName, keys, Set.of());
    }

    private static List<RuntimeRegistryHelperSpec> resolveRegistryHelpers(Set<String> registryHelpers) {
        if (registryHelpers == null || registryHelpers.isEmpty()) {
            return List.of();
        }
        List<String> helperKeys = new ArrayList<>(registryHelpers);
        helperKeys.sort(String::compareTo);
        List<RuntimeRegistryHelperSpec> specs = new ArrayList<>();
        for (String helperKey : helperKeys) {
            RuntimeRegistryHelperSpec spec = RUNTIME_REGISTRY_HELPERS.get(helperKey);
            if (spec == null) {
                throw new GradleException(
                    "Unsupported key catalog registry helper '" + helperKey + "'. Supported values: "
                        + String.join(", ", new java.util.TreeSet<>(RUNTIME_REGISTRY_HELPERS.keySet()))
                );
            }
            specs.add(spec);
        }
        return specs;
    }

    private record RuntimeRegistryHelperSpec(
        String className,
        List<String> importTypes,
        String returnType,
        String resolveExpression,
        String requireExpression
    ) {
    }
}
