package de.t14d3.rapunzellib.gradle.catalog;

import org.gradle.api.GradleException;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;

public final class RegistryCatalogGenerator {
    private RegistryCatalogGenerator() {
    }

    public static String renderJavaSource(
        String packageName,
        String className,
        String domainName,
        String sourceDescription,
        List<NamespacedKeyEntry> keys,
        String registryValueType,
        String registryKeyOwnerType,
        String registryKeyFieldName
    ) {
        CatalogCodegenSupport.requireValidPackageName(packageName, "Registry catalog");
        CatalogCodegenSupport.requireValidJavaIdentifier(className, "class name", "Registry catalog");

        String trimmedDomainName = domainName.trim();
        if (trimmedDomainName.isEmpty()) {
            throw new GradleException("Registry catalog domain name must not be blank.");
        }
        if (keys.isEmpty()) {
            throw new GradleException("Registry catalog generation requires at least one namespaced key.");
        }

        String registryValueTypeName =
            CatalogCodegenSupport.requireValidQualifiedTypeName(registryValueType, "registry value type", "Registry catalog");
        String registryKeyOwnerTypeName =
            CatalogCodegenSupport.requireValidQualifiedTypeName(registryKeyOwnerType, "registry key owner type", "Registry catalog");
        CatalogCodegenSupport.requireValidJavaIdentifier(registryKeyFieldName, "registry key field name", "Registry catalog");

        String valueType = CatalogCodegenSupport.simpleTypeName(registryValueTypeName);
        String registryKeyOwner = CatalogCodegenSupport.simpleTypeName(registryKeyOwnerTypeName);
        Map<String, List<NamespacedKeyEntry>> grouped = keys.stream().collect(
            java.util.stream.Collectors.groupingBy(
                NamespacedKeyEntry::namespace,
                java.util.LinkedHashMap::new,
                java.util.stream.Collectors.toList()
            )
        );
        Map<String, String> namespaceNames = CatalogCodegenSupport.uniqueClassNames(new ArrayList<>(grouped.keySet()));
        LinkedHashSet<String> imports = new LinkedHashSet<>(List.of(
            "de.t14d3.rapunzellib.objects.RKey",
            "de.t14d3.rapunzellib.registry.RRegistryKey",
            "de.t14d3.rapunzellib.registry.RRegistryRef",
            "java.util.Optional",
            registryValueTypeName,
            registryKeyOwnerTypeName
        ));

        StringBuilder source = new StringBuilder();
        source.append("package ").append(packageName).append(";\n\n");
        for (String importName : imports) {
            source.append("import ").append(importName).append(";\n");
        }
        source.append("\n/**\n")
            .append(" * Generated by rapunzellibGenerateRegistryCatalogs for the '").append(trimmedDomainName).append("' domain.\n")
            .append(" * Source: ").append(sourceDescription.trim()).append(".\n")
            .append(" * Catalog refs are deterministic conveniences; live registries remain the source of truth.\n")
            .append(" */\n")
            .append("public final class ").append(className).append(" {\n")
            .append("    public static final String DOMAIN = ").append(CatalogCodegenSupport.javaString(trimmedDomainName)).append(";\n")
            .append("    public static final RRegistryKey<").append(valueType).append("> REGISTRY = ")
            .append(registryKeyOwner).append(".").append(registryKeyFieldName).append(";\n\n")
            .append("    private ").append(className).append("() {\n")
            .append("    }\n\n")
            .append("    public static RRegistryRef<").append(valueType).append("> ref(RKey key) {\n")
            .append("        return REGISTRY.ref(key);\n")
            .append("    }\n\n")
            .append("    public static RRegistryRef<").append(valueType).append("> ref(String key) {\n")
            .append("        return REGISTRY.ref(key);\n")
            .append("    }\n\n")
            .append("    public static Optional<").append(valueType).append("> find(RKey key) {\n")
            .append("        return ").append(valueType).append(".find(key);\n")
            .append("    }\n\n")
            .append("    public static Optional<").append(valueType).append("> find(String key) {\n")
            .append("        return find(RKey.of(key));\n")
            .append("    }\n\n")
            .append("    public static ").append(valueType).append(" require(RKey key) {\n")
            .append("        return ").append(valueType).append(".require(key);\n")
            .append("    }\n\n")
            .append("    public static ").append(valueType).append(" require(String key) {\n")
            .append("        return require(RKey.of(key));\n")
            .append("    }\n");

        grouped.entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(entry -> {
            List<NamespacedKeyEntry> namespaceKeys = new ArrayList<>(entry.getValue());
            namespaceKeys.sort(java.util.Comparator.comparing(NamespacedKeyEntry::path));
            Map<String, String> constantNames = CatalogCodegenSupport.uniqueConstantNames(
                namespaceKeys.stream().map(NamespacedKeyEntry::path).toList()
            );

            source.append("\n")
                .append("    public static final class ").append(namespaceNames.get(entry.getKey())).append(" {\n")
                .append("        public static final String NAMESPACE = ")
                .append(CatalogCodegenSupport.javaString(entry.getKey())).append(";\n");

            for (NamespacedKeyEntry key : namespaceKeys) {
                String constantName = constantNames.get(key.path());
                source.append("\n")
                    .append("        public static final RKey ").append(constantName).append("_KEY = RKey.of(")
                    .append(CatalogCodegenSupport.javaString(key.value())).append(");\n")
                    .append("        public static final RRegistryRef<").append(valueType).append("> ").append(constantName)
                    .append(" = ref(").append(constantName).append("_KEY);\n");
            }

            source.append("\n")
                .append("        private ").append(namespaceNames.get(entry.getKey())).append("() {\n")
                .append("        }\n")
                .append("    }\n");
        });

        source.append("}\n");
        return source.toString();
    }
}
