package de.t14d3.rapunzellib.gradle.nbt;

import org.gradle.api.GradleException;
import org.yaml.snakeyaml.LoaderOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.SafeConstructor;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Pattern;

public final class RNbtSchemaGenerator {
    private static final Pattern UPPER_ACRONYM_BOUNDARY = Pattern.compile("([A-Z]+)([A-Z][a-z])");
    private static final Pattern CAMEL_CASE_BOUNDARY = Pattern.compile("([a-z0-9])([A-Z])");
    private static final Pattern NON_IDENTIFIER = Pattern.compile("[^A-Z0-9]+");
    private static final Pattern DUPLICATE_UNDERSCORES = Pattern.compile("_+");

    private RNbtSchemaGenerator() {
    }

    public static RNbtSchemaSpec parseInputFiles(Iterable<File> files) {
        List<File> sourceFiles = new ArrayList<>();
        for (File file : files) {
            if (file.isFile()) {
                sourceFiles.add(file);
            }
        }
        sourceFiles.sort(Comparator.comparing(File::getAbsolutePath));
        if (sourceFiles.isEmpty()) {
            throw new GradleException("RNbt schema generation requires at least one input file.");
        }

        String schemaName = null;
        List<RNbtSchemaEntrySpec> entries = new ArrayList<>();
        for (File file : sourceFiles) {
            RNbtSchemaSpec parsed = parseInputFile(file);
            if (schemaName == null) {
                schemaName = parsed.name();
            } else if (!schemaName.equals(parsed.name())) {
                throw new GradleException(
                    "RNbt schema input " + file.getAbsolutePath() + " declares schema '" + parsed.name()
                        + "', but previous inputs declared '" + schemaName + "'."
                );
            }
            entries.addAll(parsed.entries());
        }

        if (entries.isEmpty()) {
            throw new GradleException(
                "No RNbt schema entries found in "
                    + sourceFiles.stream().map(File::getAbsolutePath).collect(java.util.stream.Collectors.joining(", "))
                    + ". Expected a non-empty 'entries' list."
            );
        }

        RNbtSchemaSpec schema = new RNbtSchemaSpec(schemaName == null ? "" : schemaName, List.copyOf(entries));
        validateUniquePaths(schema);
        return schema;
    }

    public static String renderJavaSource(String packageName, String className, RNbtSchemaSpec schema) {
        requireValidPackageName(packageName);
        requireValidJavaIdentifier(className, "class name");
        if (schema.name().isBlank()) {
            throw new GradleException("RNbt schema name must not be blank.");
        }
        if (schema.entries().isEmpty()) {
            throw new GradleException("RNbt schema '" + schema.name() + "' must contain at least one entry.");
        }

        LinkedHashSet<String> imports = new LinkedHashSet<>(List.of(
            "de.t14d3.rapunzellib.nbt.RNbtCodec",
            "de.t14d3.rapunzellib.nbt.RNbtCodecs",
            "de.t14d3.rapunzellib.nbt.RNbtField",
            "de.t14d3.rapunzellib.nbt.RNbtPath",
            "de.t14d3.rapunzellib.nbt.RNbtSchema"
        ));
        if (schema.requiresCompoundImport()) {
            imports.add("de.t14d3.rapunzellib.nbt.RNbtCompound");
        }
        if (schema.requiresValueImport()) {
            imports.add("de.t14d3.rapunzellib.nbt.RNbtValue");
        }
        if (schema.requiresListImport()) {
            imports.add("java.util.List");
        }
        if (schema.requiresComponentImport()) {
            imports.add("net.kyori.adventure.text.Component");
        }

        List<RNbtSchemaEntrySpec> rootFields = schema.entries();
        Map<String, String> rootFieldNames = uniqueConstantNames(rootFields.stream().map(RNbtSchemaEntrySpec::key).toList());
        List<RNbtFlattenedEntrySpec> flattenedPaths = schema.flattenedEntries();
        Map<String, String> pathNames =
            uniqueConstantNames(flattenedPaths.stream().map(entry -> String.join(".", entry.segments())).toList());

        StringBuilder source = new StringBuilder();
        source.append("package ").append(packageName).append(";\n\n");
        for (String importName : imports) {
            source.append("import ").append(importName).append(";\n");
        }
        source.append("\n/**\n")
            .append(" * Generated by rapunzellibGenerateRNbtSchema for the '").append(schema.name()).append("' schema.\n")
            .append(" * Schema inputs are checked-in YAML declarations of known NBT paths.\n")
            .append(" */\n")
            .append("public final class ").append(className).append(" {\n")
            .append("    public static final String NAME = ").append(javaString(schema.name())).append(";\n")
            .append("    public static final RNbtSchema SCHEMA = RNbtSchema.of(\n")
            .append("        NAME,\n");
        for (int index = 0; index < rootFields.size(); index++) {
            RNbtSchemaEntrySpec entry = rootFields.get(index);
            String suffix = index == rootFields.size() - 1 ? "" : ",";
            source.append("        Fields.").append(rootFieldNames.get(entry.key())).append(suffix).append("\n");
        }
        source.append("    );\n\n")
            .append("    private ").append(className).append("() {\n")
            .append("    }\n\n")
            .append("    public static final class Fields {\n");

        for (RNbtSchemaEntrySpec entry : rootFields) {
            source.append("        public static final RNbtField<")
                .append(entry.codec().javaType())
                .append("> ")
                .append(rootFieldNames.get(entry.key()))
                .append(" = RNbtField.of(")
                .append(javaString(entry.key()))
                .append(", ")
                .append(entry.codec().codecExpression())
                .append(");\n");
        }

        source.append("\n")
            .append("        private Fields() {\n")
            .append("        }\n")
            .append("    }\n\n")
            .append("    public static final class Paths {\n");

        for (RNbtFlattenedEntrySpec entry : flattenedPaths) {
            String joinedSegments = String.join(".", entry.segments());
            String arguments = entry.segments().stream().map(RNbtSchemaGenerator::javaString).collect(java.util.stream.Collectors.joining(", "));
            source.append("        public static final RNbtPath<")
                .append(entry.codec().javaType())
                .append("> ")
                .append(pathNames.get(joinedSegments))
                .append(" = path(")
                .append(entry.codec().codecExpression())
                .append(", ")
                .append(arguments)
                .append(");\n");
        }

        source.append("\n")
            .append("        private Paths() {\n")
            .append("        }\n")
            .append("    }\n\n")
            .append("    private static <T> RNbtPath<T> path(RNbtCodec<T> codec, String first, String... rest) {\n")
            .append("        RNbtPath<T> path = RNbtPath.of(codec, first);\n")
            .append("        for (String key : rest) {\n")
            .append("            path = path.key(key);\n")
            .append("        }\n")
            .append("        return path;\n")
            .append("    }\n")
            .append("}\n");
        return source.toString();
    }

    private static RNbtSchemaSpec parseInputFile(File file) {
        Yaml yaml = new Yaml(new SafeConstructor(new LoaderOptions()));
        Object loaded;
        try {
            loaded = yaml.load(Files.readString(file.toPath(), StandardCharsets.UTF_8));
        } catch (Exception ex) {
            throw new GradleException("Failed to parse RNbt schema input " + file.getAbsolutePath() + ": " + ex.getMessage(), ex);
        }

        Map<String, Object> root = requireMap(loaded, file, "<root>");
        String name = requireString(root.get("name"), file, "name");
        List<RNbtSchemaEntrySpec> entries = parseEntries(root.get("entries"), file, "entries");
        return new RNbtSchemaSpec(name, entries);
    }

    private static List<RNbtSchemaEntrySpec> parseEntries(Object value, File file, String context) {
        List<Object> entries = requireList(value, file, context);
        if (entries.isEmpty()) {
            throw new GradleException("RNbt schema " + context + " in " + file.getAbsolutePath() + " must not be empty.");
        }

        List<RNbtSchemaEntrySpec> parsed = new ArrayList<>();
        for (int index = 0; index < entries.size(); index++) {
            parsed.add(parseEntry(requireMap(entries.get(index), file, context + "[" + index + "]"), file, context + "[" + index + "]"));
        }
        return parsed;
    }

    private static RNbtSchemaEntrySpec parseEntry(Map<String, Object> rawEntry, File file, String context) {
        String key = requireString(rawEntry.get("key"), file, context + ".key");
        String typeName = requireString(rawEntry.get("type"), file, context + ".type").toLowerCase(Locale.ROOT);
        CodecSpec codec = parseCodec(typeName, rawEntry.get("elementType"), file, context);
        List<RNbtSchemaEntrySpec> children;
        Object rawChildren = rawEntry.get("children");
        if (rawChildren == null) {
            children = List.of();
        } else {
            if (!(codec instanceof ScalarCodecSpec scalarCodec) || scalarCodec.kind() != ScalarCodecKind.COMPOUND) {
                throw new GradleException(
                    "RNbt schema " + context + " in " + file.getAbsolutePath() + " declares children for non-compound entry '" + key + "'."
                );
            }
            children = parseEntries(rawChildren, file, context + ".children");
        }
        return new RNbtSchemaEntrySpec(key, codec, children);
    }

    private static CodecSpec parseCodec(String typeName, Object rawElementType, File file, String context) {
        return switch (typeName) {
            case "string" -> new ScalarCodecSpec(ScalarCodecKind.STRING);
            case "byte" -> new ScalarCodecSpec(ScalarCodecKind.BYTE);
            case "short" -> new ScalarCodecSpec(ScalarCodecKind.SHORT);
            case "int" -> new ScalarCodecSpec(ScalarCodecKind.INT);
            case "long" -> new ScalarCodecSpec(ScalarCodecKind.LONG);
            case "float" -> new ScalarCodecSpec(ScalarCodecKind.FLOAT);
            case "double" -> new ScalarCodecSpec(ScalarCodecKind.DOUBLE);
            case "boolean" -> new ScalarCodecSpec(ScalarCodecKind.BOOLEAN);
            case "byte_array" -> new ScalarCodecSpec(ScalarCodecKind.BYTE_ARRAY);
            case "int_array" -> new ScalarCodecSpec(ScalarCodecKind.INT_ARRAY);
            case "long_array" -> new ScalarCodecSpec(ScalarCodecKind.LONG_ARRAY);
            case "compound" -> new ScalarCodecSpec(ScalarCodecKind.COMPOUND);
            case "value" -> new ScalarCodecSpec(ScalarCodecKind.VALUE);
            case "component" -> new ScalarCodecSpec(ScalarCodecKind.COMPONENT);
            case "list" -> {
                String elementType = requireString(rawElementType, file, context + ".elementType").toLowerCase(Locale.ROOT);
                yield new ListCodecSpec(parseCodec(elementType, null, file, context + ".elementType"));
            }
            default -> throw new GradleException(
                "Unsupported RNbt schema type '" + typeName + "' at " + file.getAbsolutePath() + " (" + context + ".type)."
            );
        };
    }

    private static void validateUniquePaths(RNbtSchemaSpec schema) {
        LinkedHashSet<String> seen = new LinkedHashSet<>();
        for (RNbtFlattenedEntrySpec entry : schema.flattenedEntries()) {
            String path = String.join(".", entry.segments());
            if (!seen.add(path)) {
                throw new GradleException("Duplicate RNbt schema entry '" + path + "' in schema '" + schema.name() + "'.");
            }
        }
    }

    private static Map<String, String> uniqueConstantNames(List<String> values) {
        Map<String, Integer> used = new LinkedHashMap<>();
        Map<String, String> names = new LinkedHashMap<>();
        for (String value : values) {
            String baseName = sanitizeConstantName(value);
            int count = used.getOrDefault(baseName, 0) + 1;
            used.put(baseName, count);
            names.put(value, count == 1 ? baseName : baseName + "_" + count);
        }
        return names;
    }

    private static String sanitizeConstantName(String value) {
        String normalized = value;
        normalized = UPPER_ACRONYM_BOUNDARY.matcher(normalized).replaceAll("$1_$2");
        normalized = CAMEL_CASE_BOUNDARY.matcher(normalized).replaceAll("$1_$2");
        normalized = normalized.toUpperCase(Locale.ROOT);
        normalized = NON_IDENTIFIER.matcher(normalized).replaceAll("_").replaceAll("^_+|_+$", "");
        normalized = DUPLICATE_UNDERSCORES.matcher(normalized).replaceAll("_");
        if (normalized.isBlank()) {
            return "PATH";
        }
        return Character.isDigit(normalized.charAt(0)) ? "PATH_" + normalized : normalized;
    }

    private static void requireValidPackageName(String packageName) {
        String trimmed = packageName.trim();
        if (trimmed.isEmpty()) {
            throw new GradleException("RNbt schema package name must not be blank.");
        }
        for (String segment : trimmed.split("\\.")) {
            requireValidJavaIdentifier(segment, "package segment");
        }
    }

    private static void requireValidJavaIdentifier(String value, String label) {
        if (value.isEmpty()) {
            throw new GradleException("RNbt schema " + label + " must not be blank.");
        }
        if (!Character.isJavaIdentifierStart(value.charAt(0))) {
            throw new GradleException("Invalid RNbt schema " + label + " '" + value + "'.");
        }
        for (int index = 1; index < value.length(); index++) {
            if (!Character.isJavaIdentifierPart(value.charAt(index))) {
                throw new GradleException("Invalid RNbt schema " + label + " '" + value + "'.");
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> requireMap(Object value, File file, String context) {
        if (!(value instanceof Map<?, ?> rawMap)) {
            throw new GradleException("Expected RNbt schema map at " + file.getAbsolutePath() + " (" + context + ").");
        }
        Map<String, Object> map = new LinkedHashMap<>();
        rawMap.forEach((key, entryValue) -> map.put(String.valueOf(key), (Object) entryValue));
        return map;
    }

    @SuppressWarnings("unchecked")
    private static List<Object> requireList(Object value, File file, String context) {
        if (!(value instanceof List<?> rawList)) {
            throw new GradleException("Expected RNbt schema list at " + file.getAbsolutePath() + " (" + context + ").");
        }
        return (List<Object>) rawList;
    }

    private static String requireString(Object value, File file, String context) {
        String stringValue = value instanceof String string ? string.trim() : null;
        if (stringValue == null || stringValue.isEmpty()) {
            throw new GradleException("Expected non-blank RNbt schema string at " + file.getAbsolutePath() + " (" + context + ").");
        }
        return stringValue;
    }

    private static String javaString(String value) {
        StringBuilder builder = new StringBuilder("\"");
        for (int index = 0; index < value.length(); index++) {
            char ch = value.charAt(index);
            switch (ch) {
                case '\\' -> builder.append("\\\\");
                case '"' -> builder.append("\\\"");
                case '\n' -> builder.append("\\n");
                case '\r' -> builder.append("\\r");
                case '\t' -> builder.append("\\t");
                default -> builder.append(ch);
            }
        }
        builder.append('"');
        return builder.toString();
    }
}
