package de.t14d3.rapunzellib.gradle;

import java.util.List;

public final class InitTemplateRenderer {
    private InitTemplateRenderer() {
    }

    public static List<GeneratedTextFile> render(InitTemplateSpec spec) {
        return List.of(
            new GeneratedTextFile("README.md", renderReadme(spec)),
            new GeneratedTextFile("settings.gradle.kts", renderSettings(spec)),
            new GeneratedTextFile("build.gradle.kts", renderRootBuild(spec)),
            new GeneratedTextFile("common/build.gradle.kts", renderCommonBuild()),
            new GeneratedTextFile("common/src/main/resources/messages.yml", renderMessages(spec)),
            new GeneratedTextFile("common/src/main/resources/config.yml", renderConfig()),
            new GeneratedTextFile(
                "common/src/main/java/%s/common/CommonFeature.java".formatted(spec.packagePath()),
                renderCommonFeatureSource(spec)
            ),
            new GeneratedTextFile("platform-paper/build.gradle.kts", renderPaperBuild(spec)),
            new GeneratedTextFile(
                "platform-paper/src/main/java/%s/paper/PaperBootstrapPlugin.java".formatted(spec.packagePath()),
                renderPaperBootstrapSource(spec)
            ),
            new GeneratedTextFile("platform-velocity/build.gradle.kts", renderVelocityBuild()),
            new GeneratedTextFile(
                "platform-velocity/src/main/java/%s/velocity/VelocityBootstrapPlugin.java".formatted(spec.packagePath()),
                renderVelocityBootstrapSource(spec)
            )
        );
    }

    private static String renderReadme(InitTemplateSpec spec) {
        return """
            # %s

            Generated by RapunzelLib Gradle plugin as a multi-module starter:

            - `common` shared logic
            - `platform-paper` Paper entry module
            - `platform-velocity` Velocity entry module
            """.formatted(spec.projectName()) + "\n";
    }

    private static String renderSettings(InitTemplateSpec spec) {
        return """
            rootProject.name = "%s"

            include(
                "common",
                "platform-paper",
                "platform-velocity"
            )
            """.formatted(spec.projectName()) + "\n";
    }

    private static String renderRootBuild(InitTemplateSpec spec) {
        return """
            plugins {
                id("java") apply false
            }

            allprojects {
                group = "%s"
                version = "1.0.0-SNAPSHOT"

                repositories {
                    mavenCentral()
                    maven("https://repo.papermc.io/repository/maven-public/")
                }
            }

            subprojects {
                plugins.withId("java") {
                    extensions.configure<JavaPluginExtension> {
                        toolchain.languageVersion.set(JavaLanguageVersion.of(21))
                    }
                }
            }
            """.formatted(spec.basePackageName()) + "\n";
    }

    private static String renderCommonBuild() {
        return """
            plugins {
                `java-library`
            }

            dependencies {
                api("de.t14d3.rapunzellib:api")
                implementation("de.t14d3.rapunzellib:events")
                implementation("de.t14d3.rapunzellib:gui")
                implementation("de.t14d3.rapunzellib:nbt")
                implementation("de.t14d3.rapunzellib:commands")
            }
            """ + "\n";
    }

    private static String renderMessages(InitTemplateSpec spec) {
        return """
            prefix: "<gray>[<gold>%s</gold>]</gray> "
            example:
              hello: "<green>Hello, <name>!</green>"
            """.formatted(spec.projectName()) + "\n";
    }

    private static String renderConfig() {
        return """
            network:
              # Set this on backend servers when the runtime cannot infer the external name.
              # serverName: "paper-1"

              # Override the logical proxy node name when it should differ from the default.
              # proxyServerName: "velocity"

              # plugin_only, plugin_first, redis_first, redis_only, rpc_server_first, rpc_server_only
              transportPriority: "plugin_first"

              redis:
                # host: "127.0.0.1"
                # port: 6379
                # transportChannel: "rapunzellib:bridge"

              rpcServer:
                enabled: false
                # host: "127.0.0.1"
                # port: 25566
            example:
              enabled: true
            """ + "\n";
    }

    private static String renderCommonFeatureSource(InitTemplateSpec spec) {
        return """
            package %s.common;

            import de.t14d3.rapunzellib.commands.CommandFeatures;
            import de.t14d3.rapunzellib.events.EventFeatures;
            import de.t14d3.rapunzellib.gui.GuiFeatures;
            import de.t14d3.rapunzellib.nbt.NbtFeatures;

            public final class CommonFeature {
                private CommonFeature() {
                }

                public static void install() {
                    EventFeatures.install();
                    CommandFeatures.install();
                    GuiFeatures.install();
                    NbtFeatures.install();
                }
            }
            """.formatted(spec.basePackageName()) + "\n";
    }

    private static String renderPaperBuild(InitTemplateSpec spec) {
        return """
            plugins {
                `java`
            }

            dependencies {
                implementation(project(":common"))
                implementation("de.t14d3.rapunzellib:platform-paper")
                implementation("de.t14d3.rapunzellib:events-paper")
                implementation("de.t14d3.rapunzellib:commands-paper")
                implementation("de.t14d3.rapunzellib:gui-paper")
                implementation("de.t14d3.rapunzellib:nbt-paper")
                compileOnly("io.papermc.paper:paper-api:%s")
            }
            """.formatted(spec.version()) + "\n";
    }

    private static String renderPaperBootstrapSource(InitTemplateSpec spec) {
        return """
            package %s.paper;

            import %s.common.CommonFeature;
            import de.t14d3.rapunzellib.Rapunzel;
            import de.t14d3.rapunzellib.platform.paper.PaperRapunzelBootstrap;
            import org.bukkit.plugin.java.JavaPlugin;

            public final class PaperBootstrapPlugin extends JavaPlugin {
                @Override
                public void onEnable() {
                    PaperRapunzelBootstrap.bootstrap(this);
                    CommonFeature.install();
                }

                @Override
                public void onDisable() {
                    Rapunzel.shutdown(this);
                }
            }
            """.formatted(spec.basePackageName(), spec.basePackageName()) + "\n";
    }

    private static String renderVelocityBuild() {
        return """
            plugins {
                `java`
            }

            dependencies {
                implementation(project(":common"))
                implementation("de.t14d3.rapunzellib:platform-velocity")
            }
            """ + "\n";
    }

    private static String renderVelocityBootstrapSource(InitTemplateSpec spec) {
        return """
            package %s.velocity;

            import com.velocitypowered.api.plugin.Plugin;
            import com.velocitypowered.api.proxy.ProxyServer;
            import de.t14d3.rapunzellib.platform.velocity.VelocityRapunzelBootstrap;
            import org.slf4j.Logger;

            import javax.inject.Inject;
            import java.nio.file.Path;

            @Plugin(id = "%s", name = "%s", version = "1.0.0-SNAPSHOT")
            public final class VelocityBootstrapPlugin {
                @Inject
                public VelocityBootstrapPlugin(ProxyServer proxyServer, Logger logger, Path dataDirectory) {
                    VelocityRapunzelBootstrap.bootstrap(this, proxyServer, logger, dataDirectory);
                }
            }
            """.formatted(spec.basePackageName(), spec.pluginId(), spec.projectName()) + "\n";
    }
}
