modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-2.1"

[[mods]]
modId="rapunzellib_livetest_neoforge"
version="${version}"
displayName="RapunzelLib (NeoForge LiveTest)"
description="NeoForge LiveTest platform implementation for RapunzelLib."
authors="t14d3"
