package de.t14d3.rapunzellib.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

abstract class InitTemplateTask : DefaultTask() {
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Input
    abstract val basePackage: Property<String>

    @get:Input
    abstract val projectName: Property<String>

    @TaskAction
    fun generate() {
        val out = outputDir.get().asFile
        out.mkdirs()

        write(out.resolve("README.md"), """
            # ${projectName.get()}

            Generated by RapunzelLib Gradle plugin.
        """.trimIndent() + "\n")

        write(out.resolve("src/main/resources/messages.yml"), """
            prefix: "<gray>[<gold>${projectName.get()}</gold>]</gray> "
            example:
              hello: "<green>Hello, <name>!</green>"
        """.trimIndent() + "\n")

        write(out.resolve("src/main/resources/config.yml"), """
            example:
              enabled: true
        """.trimIndent() + "\n")

        write(out.resolve("src/main/java/${basePackage.get().replace('.', '/')}/Example.java"), """
            package ${basePackage.get()};

            public final class Example {
                private Example() {}
            }
        """.trimIndent() + "\n")
    }

    private fun write(file: File, content: String) {
        file.parentFile?.mkdirs()
        if (!file.exists()) {
            file.writeText(content)
        }
    }
}
